### ISSUE TITLE
A daylight savings mechanism?

### ISSUE THREAD

**Issue by applecuckoo** [ErikAndren/sntp#6]
Hi there, I've just been trying to get RiiConnect24 working on my Wii and this very piece of homebrew was [recommended](https://wii.guide/rtc) as something to run beforehand. Frustratingly, the current time zone in my area is UTC+13 which can't be set as a valid option. As a result, the Forecast Channel won't work since the time doesn't match up.
FYI, I've read issue #1, but I think signing up to a web API is a bit overkill for setting the time...

**Comment by ErikAndren** [comment]
Hi, I don't have the setup rigged to test this.
I have created a quick hack where I've removed the 12 zone limitation.
Please download and test here:
https://github.com/ErikAndren/sntp/blob/ErikAndren-issue-6/sntp.dol

Let me know how it works out for you.

**Comment by applecuckoo** [comment]
Thanks for the quick response - just tested it out and it solved the daylight savings problem! Closing.
